config/routes.rb
Rails.application.routes.draw do
  root 'event#index'
  resources :users
  resources :elections
  resources :candidates
  post "elections/(:id)", to: "elections#show"
  get "user/profile", to: 'users#show', as: :user_profile
  post "user/profile", to: 'users#update'
  get "register", to: "users#new", as: :register
  post "register", to: "users#create"
  resources :sessions, only: [:new, :create, :destroy]
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :user_detail, dependent: :destroy
  has_one :candidate
  has_many :votes
  has_many :vote_chains, through: :votes

  delegate *UserDetail::ATTR_METHODS, to: :user_detail

  after_create do
    self.create_user_detail 
  end

end

app/models/user/user.rb
class User::User < ApplicationRecord
  has_secure_password
  
  validates :username, presence: true, uniqueness: true

  has_one :user_user_detail, class_name: "UserDetail", foreign_key: "user_user_id"
end

app/models/user/user_detail.rb
class User::UserDetail < ApplicationRecord
  belongs_to :user_user, class_name: "User", foreign_key: "user_user_id"
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :set_user_user, only: [:show, :edit, :update, :destroy]

  # GET /user/users
  # GET /user/users.json
  def index
    @user_users = User::User.all
  end

  # GET /user/users/1
  # GET /user/users/1.json
  def show
  end

  # GET /user/users/new
  def new
    @user_user = User::User.new
  end

  # GET /user/users/1/edit
  def edit
  end

  # POST /user/users
  # POST /user/users.json
  def create
    @user_user = User::User.new(user_user_params)

    respond_to do |format|
      if @user_user.save
        format.html { redirect_to @user_user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user_user }
      else
        format.html { render :new }
        format.json { render json: @user_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user/users/1
  # PATCH/PUT /user/users/1.json
  def update
    respond_to do |format|
      if @user_user.update(user_user_params)
        format.html { redirect_to @user_user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_user }
      else
        format.html { render :edit }
        format.json { render json: @user_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user/users/1
  # DELETE /user/users/1.json
  def destroy
    @user_user.destroy
    respond_to do |format|
      format.html { redirect_to user_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_user
      @user_user = User::User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_user_params
      params.require(:user_user).permit(:username, :password, :password_confirmation)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end

  def show
    if @current_user
      @user = @current_user
    else
      redirect_to root_path, error: "Please log in to see profile details"
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if request["commit"] == "Update Password"
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        if @user.user_detail.update(user_detail_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :admin)
    end

    def user_detail_params
      params.require(:user).permit(:name, :gender, :branch, :year, :roll_number, :course, :address)
    end
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with url: user_profile_path do |form| %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit "Update Password" %>
  </div>
<% end %>

<%= form_with url: user_profile_path do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, value: "#{user.name if user.name}" %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender, value: "#{user.gender if user.gender}" %>
  </div>

  <div class="field">
    <%= form.label :branch %>
    <%= form.text_field :branch, value: "#{user.branch if user.branch}" %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year, value: "#{user.year if user.year}" %>
  </div>

  <div class="field">
    <%= form.label :roll_number %>
    <%= form.text_field :roll_number, value: "#{user.roll_number if user.roll_number}" %>
  </div>

  <div class="field">
    <%= form.label :course %>
    <%= form.text_field :course, value: "#{user.course if user.course}" %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, value: "#{user.address if user.address}" %>
  </div>

  <div class="actions">
    <%= form.submit "Update Details" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<!--<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>-->
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>E-Mail:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Department:</strong>
  <%= @user.branch %>
</p>
<p>
  <strong>Course:</strong>
  <%= @user.course %>
</p>
<p>
  <strong>Year:</strong>
  <%= @user.year %>
</p>

<%= render "form", user: @user %>