config/routes.rb
Rails.application.routes.draw do
  root 'event#index'
  resources :users
  resources :elections
  resources :candidates
  post "elections/(:id)", to: "elections#show"
  get "user/profile", to: 'users#show', as: :user_profile
  post "user/profile", to: 'users#update'
  get "register", to: "users#new", as: :register
  post "register", to: "users#create"
  resources :sessions, only: [:new, :create, :destroy]
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :user

  has_one :candidate_detail
  has_many :nominations
  has_many :elections, through: :nominations


  delegate *CandidateDetail::ATTR_METHODS, to: :candidate_detail

 after_create do
   self.create_candidate_detail
 end

end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)

    respond_to do |format|
      if @candidate.save
        format.html { redirect_to @candidate, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to @candidate, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:affiliation, :user_id)
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_with(model: candidate, local: true) do |form| %>
  <% if candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :affiliation %>
    <%= form.text_field :affiliation %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :semester %>
    <%= form.text_field :semester %>
  </div>
  <div class="field">
    <%= form.label :roll_no %>
    <%= form.text_field :roll_no %>
  </div>
  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department %>
  </div>
  <div class="field">
    <%= form.label :section %>
    <%= form.text_field :section %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing Candidate</h1>

<%= render 'form', candidate: @candidate %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candidates</h1>

<table>
  <thead>
    <tr>
      <th>  Affiliation</th>

      <th>   User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
 if user==admin
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.affiliation %></td>
        <td><%= candidate.user.name %></td>
        <div class="btn btn-default">
          <td><%= link_to 'Show', candidate, :class => "btn" %></td>
        <!--  <td><%= link_to 'Edit', edit_candidate_path(candidate), :class => "btn" %></td>
            <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn"  %></td>-->
        </div>


      </tr>
    <% end %>
    else
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.affiliation %></td>
        <td><%= candidate.user.name %></td>
        <div class="btn btn-default">
          <td><%= link_to 'Show', candidate, :class => "btn" %></td>
         <td><%= link_to 'Edit', edit_candidate_path(candidate), :class => "btn" %></td>
            <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn"  %></td>
        </div>


      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="btn btn-warning">
  <%= link_to 'New Candidate', new_candidate_path, :class => "btn" %>

</div>

app/views/candidates/new.html.erb
<h1>New Candidate</h1>

<%= render 'form', candidate: @candidate %>

<%= link_to 'Back', candidates_path %>

app/views/candidates/show.html.erb
<!--
<div class = "container"
  <p id="notice"><%= notice %></p>
  <p>
    <strong>Affiliation:</strong>
    <%= @candidate.affiliation %>
  </p>



  <p>
    <strong>Candidate Email:</strong>
    <%= @candidate.user.email %>
  </p>
  <p>
    <strong>Candidate Gender:</strong>
    <%= @candidate.user.gender %>
  </p>
  <p>
    <strong>Candidate Branch:</strong>
    <%= @candidate.user.branch %>
  </p>
  <p>
    <strong>Candidate Course:</strong>
    <%= @candidate.user.course %>
  </p>

  <p>
    <strong>CGPA:</strong>
    <%= @candidate.cgpa %>
  </p>
  <p>
    <strong>Past Experience:</strong>
    <%= @candidate.experience %>
  </p>

  <p>
    <strong>About Me:</strong>
    <%= @candidate.about_me %>
  </p>
<div class="btn btn-default">
  <%= link_to 'Back', candidates_path, :class => "btn" %>

</div>
</div> -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2 col-md-2">
            <img src="http://thetransformedmale.files.wordpress.com/2011/06/bruce-wayne-armani.jpg"
            alt="" class="img-rounded img-responsive" />
        </div>
        <div class="col-sm-4 col-md-4">
            <blockquote>
              <%= @candidate.user.name %><small><cite title="Source Title">NITK,Surathkal <i class="glyphicon glyphicon-map-marker"></i></cite></small>
            </blockquote>
            <p> <i class="glyphicon glyphicon-envelope"></i>       <%= @candidate.affiliation %> <br>
  <%= @candidate.user.email %> <br>    <%= @candidate.user.branch %> <br>
            <strong>Candidate Gender:</strong>

              <%= @candidate.user.gender %>    <br>
               <%= @candidate.user.course %>  <br>
               <strong>CGPA:</strong>
               <%= @candidate.cgpa %>    <br>
               <strong>Past Experience:</strong>
               <%= @candidate.experience %> <br>
               <strong>About Me:</strong>
               <%= @candidate.about_me %> <br>

        </div>


    </div>
</div>
<div class="btn btn-default">
  <%= link_to 'Back', candidates_path, :class => "btn" %>

</div>