config/routes.rb
Rails.application.routes.draw do
  root 'event#index'
  resources :users
  resources :elections
  resources :candidates
  post "elections/(:id)", to: "elections#show"
  get "user/profile", to: 'users#show', as: :user_profile
  post "user/profile", to: 'users#update'
  get "register", to: "users#new", as: :register
  post "register", to: "users#create"
  resources :sessions, only: [:new, :create, :destroy]
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :user

  has_one :candidate_detail
  has_many :nominations
  has_many :elections, through: :nominations


  delegate *CandidateDetail::ATTR_METHODS, to: :candidate_detail

 after_create do
   self.create_candidate_detail
 end

end

app/models/candidate_detail.rb
class CandidateDetail < ApplicationRecord
  belongs_to :candidate
    ATTR_METHODS = [:cgpa, :cgpa=,:experience, :experience=,:manifesto, :manifesto=,:about_me,:about_me=]
end

app/models/election.rb
class Election < ApplicationRecord
  belongs_to :candidate, optional: true

  has_one :vote_chain
  has_many :nominations
  has_many :candidates, through: :nominations

  after_create do
    create_vote_chain
    Event.create(content: "#{position} #{session} has been announced!")
  end

  def add_vote(user, candidate)
    vote_chain.add_vote(user, candidate)
  end

  def add_candidate(candidate)
    Nomination.create(election: self, candidate: candidate)
  end

  def in_progress?
    Time.now.between?(election_start, election_end)
  end

  def over?
    Time.now > election_end
  end
  
  def started?
    Time.now < election_start
  end

  def transactions
    file_path = Rails.root.join("public", "transactions", "#{id}.csv")
    if !File.exists? file_path
      attributes = %w{id data created_at updated_at prev_hash}
      CSV.open(file_path, "w",
              write_headers: true,
              headers: attributes) do |csv|

        vote_chain.votes.each do |vote|
          csv << attributes.map{ |attr| vote.send(attr) }
        end
      end
    end
    return file_path
  end

  def demographics
    file_path = Rails.root.join("public", "demographics", "#{id}.csv")
    if !File.exists? file_path
      attributes = %{voted_for gender branch year address}
      CSV.open(file_path, "w",
               write_headers: true,
               headers: attributes) do |csv|
        vote_chain.votes.each do |vote|
          voter = vote.voter
          row = [vote.data, voter.gender, voter.branch, voter.year, voter.address]
          csv << row
        end
      end
    end
    return file_path
  end

  def candidates_csv
    file_path = Rails.root.join("public", "candidates", "#{id}.csv")
    if !File.exists? file_path
      attributes = %{id name}
      CSV.open(file_path, "w",
               write_headers: true,
               headers: attributes) do |csv|
        candidates.each do |candidate|
          row = [candidate.id, candidate.user.name]
          csv << row
        end
       end
    end
    return file_path
  end
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/nomination.rb
class Nomination < ApplicationRecord
  belongs_to :candidate
  belongs_to :election

  after_create do
    Event.create(content: "#{candidate.user.name} has been nominated for #{election.position} #{election.session}")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :user_detail, dependent: :destroy
  has_one :candidate
  has_many :votes
  has_many :vote_chains, through: :votes

  delegate *UserDetail::ATTR_METHODS, to: :user_detail

  after_create do
    self.create_user_detail 
  end

end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  belongs_to :user

  ATTR_METHODS = [:email, :email=,:gender, :gender=,:branch, :branch=,:course, :course=,:year, :year=,:section, :section=,:block, :block=,:name,:name=, :roll_number, :roll_number=, :address, :address=]

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :vote_chain
  belongs_to :user

  alias_attribute :voter, :user

  # Proof Of Work Function - Whether hash contains substring data

  after_create do
    create_genesis
  end

  def compute_hash
    loop do
      sha = Digest::SHA256.new
      prev_hash = "" if prev_hash.nil?
      sha.update(data.to_s + id.to_s + created_at.to_s + updated_at.to_s + prev_hash)
      if sha.hexdigest.include? data.to_s
        curr_hash = sha.hexdigest
        update!
      end
    end
  end

  def create_genesis
    sha = Digest::SHA256.new
    sha.update(data.to_s + id.to_s + created_at.to_s + updated_at.to_s)
    return
  end
end

app/models/vote_chain.rb
class VoteChain < ApplicationRecord
  belongs_to :election
  serialize :vote_count, Hash
  has_many :votes
  has_many :users, through: :votes

  alias_attribute :voters, :users

  after_create do 
    votes.create(data: -1)
  end

  def add_vote(voter, candidate)
    votes.create(data: candidate.id, user: voter, prev_hash: votes.last.hash)
    Event.create(content: "A vote with hash #{votes.last.hash} has been cast in elections for #{election.position} #{election.session}")
  end

  def add_candidate(candidate)
    vote_count[candidate] = 0
    update
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end

  def show
    if @current_user
      @user = @current_user
    else
      redirect_to root_path, error: "Please log in to see profile details"
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if request["commit"] == "Update Password"
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        if @user.user_detail.update(user_detail_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :admin)
    end

    def user_detail_params
      params.require(:user).permit(:name, :gender, :branch, :year, :roll_number, :course, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/elections_helper.rb
module ElectionsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackathon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "style" %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  </head>

  <body>
  <h1>NITK Online Voting Portal</h1>

    <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
        <div class="container-fluid">
            <a class = "navbar-brand" href="https://www.nitk.ac.in"> <img src="https://upload.wikimedia.org/wikipedia/en/c/cc/NITK_Emblem.png" alt="logo" width="60" height="70"> </a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarResponsive">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                  <div class = "row">
                    <ul class="navbar-nav ml-auto">
                      <div class = "col-sm-2">
                        <li class="nav-item">
                          <%= link_to "Home", root_path %>
                        </li>
                      </div>

                      <div class ="col-sm-2">
                        <li class="nav-item">
                          <%= link_to "Profile", user_profile_path %>
                        </li>
                      </div>

                      <div class="col-sm-3">
                        <li class="nav-item">
                          <%= link_to "Elections", elections_path %>
                        </li>
                      </div>

                      <div class = "col-sm-3">
                        <li class="nav-item">
                          <%= link_to "Candidates", candidates_path %>
                        </li>
                      </div>

                      <div class="col-sm-3">
                        <% if @current_user %>
                          <li class="nav-item">
                            <%= link_to "Log Out", logout_path  %>
                          </li>
                        <% else %>
                          <li class="nav-item">
                            <%= link_to "Log In", login_path  %>
                          </li>
                        <% end %>
                      </div>
                    </div>
                  </ul>
                </div>
        </div>
    </nav>

<%= yield %>
  </body>
</html>